### ISSUE TITLE
[Enhancement]: Build using future snapcraft releases to test them

### ISSUE THREAD

**Issue by popey** [snapcrafters/ci#12]
### What changes would you like?

Snapcraft is a crucial tool for our work. When new releases of snapcraft are published in a non-stable channel, we should test it against all the yaml files we have. There are at least two benefits as I see it:

* Snapcraft itself gets more extensive testing, benefiting the upstream developers and the wider community
* We become more aware of breaking or other changes in the primary tools we use
* We can update the configuration to take account of new features in snapcraft
* We can point at up-to-date packages, which other packagers can learn from

We should not gate our package releases on this. Keep an eye on packages that fail, so we may resolve issues or prepare fixes for when the next snapcraft goes into stable.

### Any extra information?

Probably the simplest thing to do is build using snapcraft from the candidate channel.

**Comment by jnsgruk** [comment]
This was fixed in #27 - which should allow snap authors to opt into testing non-default versions of snapcraft, either by default, or in a separate workflow depending on their taste :)

**Comment by jnsgruk** [comment]
(As a follow up, we could include a modification that always tests `latest/candidate` if we decide that's a good path)
